apiVersion: apps/v1
kind: Deployment
metadata:
  name: sofkabank-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sofkabanf-app-2
  template:
    metadata:
      labels:
        app: sofkabanf-app-2
    spec:
      containers:
      - name: sofkabanf-app-2
        image: rcarvajalf/sofkabankapps:latest
        ports:
        - containerPort: 8080
        env:
        - name: D_HOSTDB
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: D_HOSTDB
        - name: D_PORTDB_L
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: D_PORTDB_L
        - name: D_DBMONGO
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: D_DBMONGO
        - name: D_RABBITURL
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: D_RABBITURL
        - name: D_PORTAPP_L
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: D_PORTAPP_L
        - name: D_SUCURSAL
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: D_SUCURSAL                                                                      
        - name: D_DEPOSITO
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: D_DEPOSITO
        - name: D_CUENTA
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: D_CUENTA
        - name: D_FISICA
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: D_FISICA
        - name: D_WEB
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: D_WEB

---
apiVersion: v1
kind: Service
metadata:
  name: sofkabanf-app-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:            
    app: sofkabanf-app-2